#!/usr/bin/env python3
import json, csv

INP = "/Users/devanshasawa/Desktop/SEO by Devansh/Backlink gets Automated/projects/testlify/asset-engine/competitor-study/_work/g3_in/answer-bait-what-is-how-it-wor.tsv"
OUT = "/Users/devanshasawa/Desktop/SEO by Devansh/Backlink gets Automated/projects/testlify/asset-engine/competitor-study/_work/g3_ideas/answer-bait-what-is-how-it-wor.jsonl"

rows = {}
with open(INP) as f:
    r = csv.reader(f, delimiter="\t")
    next(r)
    for row in r:
        if not row: continue
        rows[row[0]] = {"fit": row[1], "dom": int(row[2]), "asset": row[3]}

# (idea, brand_fit, our_subject, [rowids]) — every RowID exactly once.
# SKIP rows folded into the cluster they duplicate:
#   536->ROI calc(527); 543,625->Test-type selector(529); 593->Free test-prep simulator(551)
C = [
 ("How AI Hiring Assessments Actually Work: Scoring, Proctoring & Bias Safeguards Explained","ADJACENT",
  "AI in hiring — how it works & what works",
  ["287","1337","304","307","308","337","1343","436","1510","74","97","1423","2330","2407","2414"]),
 ("AI in Talent Acquisition: Complete Guide to AI Pre-Screening, Interviews & Proctoring","CORE",
  "AI in talent acquisition — complete guide",
  ["2329","2418"]),
 ("11 Practical Applications of AI in Candidate Screening & Assessment (with implementation checklist)","TRANSPLANT",
  "AI in hiring — applications & automation",
  ["323","349","407"]),
 ("The Future of AI in Hiring Assessments: Deepfake Detection, Adaptive Testing & What's Next","ADJACENT",
  "AI in hiring — future & trends",
  ["1425","1426"]),
 ("AI Hiring Bias Audit Checklist: 25 Questions to Evaluate Any AI Screening or Interview Tool","CORE",
  "AI hiring tools — bias audit & evaluation",
  ["1341","1991","853","1071"]),
 ("AI Screening Tool Buyer's Guide: Validity Evidence, Adverse Impact Data & Vendor Scorecard","CORE",
  "AI screening tools — buyer's guide & comparison",
  ["400","2206","2293"]),
 ("AI Interviewer Explained: How It Works, Bias Risks, Candidate Experience & Vendor Evaluation","CORE",
  "AI interviewer — explainer, ROI & deployment",
  ["2408","2402","2404","2409","2426","2434","2411"]),
 ("How Online Proctoring Detects Cheating: AI Detection Methods, False-Positive Rates & Platform Comparison","CORE",
  "Proctoring & assessment integrity",
  ["1145","760","73","2312","2314","2316","2323","2352","2457"]),
 ("Assessment & Interview Technology Trends Reshaping Hiring (with buyer guidance)","ADJACENT",
  "Hiring tech trends report",
  ["422","561","1856","1809","1502","516","104"]),
 ("State of Skills-Based Hiring 2026: Adoption, Completion Benchmarks & Quality-of-Hire Data","ADJACENT",
  "State of skills-based hiring — annual report",
  ["271","1336","784","1574","1844","1860","1975","2011","2392","617","925"]),
 ("Skills-Based Hiring Statistics: 60+ Data Points on Assessment Accuracy, Quality-of-Hire & Bias","TRANSPLANT",
  "Skills-based hiring statistics",
  ["1429","130","255","1503"]),
 ("State of Hiring Assessment: 50 Original Statistics on Skills Tests, AI Interviews & Screening Outcomes","CORE",
  "State of hiring assessment — statistics report",
  ["109","129","253","254"]),
 ("Hiring Assessment Statistics 2026: 100+ Data Points with Primary & Cited Sources","CORE",
  "Hiring assessment statistics hub",
  ["2290"]),
 ("AI in Recruitment 2026: Benchmark Study on Adoption, Time-to-Hire Gains & Bias Outcomes","CORE",
  "AI in recruitment — benchmark study",
  ["2271","2350","2331","2383","2384","2389","1948","1966"]),
 ("AI Candidate Experience Benchmark: Completion, Satisfaction & Drop-Off Data by AI Feature","CORE",
  "AI candidate experience benchmark",
  ["2292"]),
 ("Recruiting Metrics Benchmark Report: What 'Good' Looks Like for Key Hiring Metrics (with Assessment KPIs)","CORE",
  "Recruiting metrics benchmark report",
  ["289","302","371","428","966","106","2355","501","468","1554"]),
 ("Hiring Metrics Master Guide: 20 KPIs with Benchmarks, Formulas & Assessment-Quality Tracking","CORE",
  "Hiring metrics master guide & glossary",
  ["315","374","1569","1374","669","1105"]),
 ("Hiring Assessment Metrics Calculator: 22 KPIs Defined, Benchmarked & Interactive","CORE",
  "Hiring metrics calculator (interactive)",
  ["2317","1568","2340"]),
 ("Time-to-Hire: Definition, Benchmarks, Formula & How Assessments Reduce It (with Industry Data)","CORE",
  "Time-to-hire benchmarks & data",
  ["1477","395","1912","1484"]),
 ("Cost-per-Hire Benchmarks by Industry & Role: How Skills-Based Assessments Cut Screening Costs","CORE",
  "Cost-per-hire benchmarks",
  ["379","1540"]),
 ("Bad Hire Cost Calculator: Estimate Your True Cost by Role, Seniority & Industry","TRANSPLANT",
  "Cost of a bad hire / turnover calculator",
  ["1954","75","1485","406"]),
 ("The ROI of Pre-Employment Skills Assessments: Calculate Return Including Quality-of-Hire & Time-to-Hire","TRANSPLANT",
  "Pre-employment testing ROI",
  ["1501","1365","681","1483","1847"]),
 ("Pre-Employment Testing ROI Calculator + Benefit Benchmarks by Role (with Sample Questions)","CORE",
  "Pre-employment testing ROI calculator",
  ["527","536"]),
 ("Hiring Analytics 101: Measuring Assessment Quality, Predictive Validity & Funnel Performance","ADJACENT",
  "Hiring analytics & predictive validity",
  ["377","480","999"]),
 ("People Analytics for Hiring: Measure Assessment Quality & Predict Quality-of-Hire","ADJACENT",
  "People analytics for hiring",
  ["364"]),
 ("In-House Hiring vs. Recruitment Agencies: The Quality-of-Hire Data You Need to Decide","ADJACENT",
  "In-house vs agency decision",
  ["1492"]),
 ("Recruitment Funnel Benchmark Report: Conversion Rates by Stage + Assessment-Screen Drop-Off","CORE",
  "Recruitment funnel benchmarks",
  ["186","2356"]),
 ("Assessment-Stage Candidate Experience Benchmark: Completion, NPS, Drop-Off & Feedback Data","CORE",
  "Candidate experience — assessment stage",
  ["1356","473","585","712","648","1519","1560","1572","1611","2007","1535","1565","1590"]),
 ("Gen Z Candidate Experience Benchmark: What Hiring Practices Drive Acceptance & Drop-Off","ADJACENT",
  "Gen Z candidate experience",
  ["546","153"]),
 ("Why Candidates Ghost: The Assessment & Process Factors That Drive Drop-Off (with Calculator)","CORE",
  "Candidate ghosting & drop-off",
  ["1372"]),
 ("Candidate Rejection Done Right: Stage-by-Stage Templates + Assessment Feedback Scripts","TRANSPLANT",
  "Candidate rejection & feedback templates",
  ["1534","1621","1998"]),
 ("Bias-Resistant Hiring: A Practical Guide to Fair Assessments & Adverse Impact Measurement","ADJACENT",
  "Bias-resistant hiring guide",
  ["319","342","386","1489","1500","2429","1899","1920"]),
 ("Adverse Impact Calculator: Run the 4/5ths Rule on Your Assessment Results (with Worked Examples)","ADJACENT",
  "Adverse impact / 4-5ths calculator",
  ["403","1886","453","852"]),
 ("The Bias-in-Hiring Audit Checklist: Score Your Process Across Bias Risk Points (with Mitigation)","CORE",
  "Bias audit checklist & self-audit",
  ["541","566","586","2366"]),
 ("Cognitive Bias in Hiring: Detection Scorecards & Structured Protocols (Contrast, Halo/Horn, Attribution)","CORE",
  "Specific cognitive biases in hiring",
  ["2425","2436","2437","1953"]),
 ("Blind & Diversity Hiring: How Structured Skills Assessments Reduce Bias at the Screening Stage","CORE",
  "Diversity & blind hiring",
  ["2420","643"]),
 ("Hiring Compliance Checklist: EEOC, Adverse Impact & Pre-Employment Assessment Legal Requirements","TRANSPLANT",
  "Hiring compliance & legal checklist",
  ["300","594","680","2456","495"]),
 ("Assessment Privacy & Ethics Handbook: Consent Templates, Data Retention & GDPR/EEOC Compliance","CORE",
  "Assessment privacy & ethics",
  ["2417x"] if False else ["2417_PLACEHOLDER"] if False else ["2417a"] if False else ["2417b"] if False else ["2417c"] if False else ["2417"] if False else ["2417_"] if False else ["2417__"]),
]
# NOTE: privacy cluster handled below cleanly to avoid the contaminated id list
C[-1] = ("Assessment Privacy & Ethics Handbook: Consent Templates, Data Retention & GDPR/EEOC Compliance","CORE",
  "Assessment privacy & ethics", ["2417"])

C += [
 ("Pre-Employment Assessment Platform 101: What It Is, How It Works & How to Choose One","TRANSPLANT",
  "Pre-employment assessment 101",
  ["303","372","661","1788"]),
 ("When Should You Use Pre-Employment Assessments? A Decision Guide for Every Hiring Scenario","TRANSPLANT",
  "When to use pre-employment assessments",
  ["321"]),
 ("17 Proven Benefits of Pre-Employment Assessment Software: What the Data Actually Shows","TRANSPLANT",
  "Benefits of pre-employment testing",
  ["1443"]),
 ("Pre-Employment Test Type Selector: Which Assessment Is Right for Your Role? (with Sample Questions)","CORE",
  "Test-type selector by role",
  ["529","543","625","605","808","660","1858","567","1838","720"]),
 ("How to Choose the Right Pre-Employment Test: Vendor-Neutral Buyer's Guide with Decision Tree","CORE",
  "How to choose a pre-employment test",
  ["811","1346","327","612","542"]),
 ("20 Best Pre-Employment Assessment & Skills Testing Platforms Compared (Buyer's Guide)","TRANSPLANT",
  "Assessment platform comparison / buyer's guide",
  ["331","1422"]),
 ("Selection Method Validity Comparison: Which Assessment to Use by Role (Interactive Tool)","CORE",
  "Selection method validity comparison",
  ["649","2308","2318","1930","1807","1876","25","1927"]),
 ("The Complete Guide to Pre-Employment Testing: All Methods, Validity Research & Legal Compliance","CORE",
  "Complete guide to pre-employment testing",
  ["118"]),
 ("Skills-to-Assessment Matrix: Map Role Requirements to the Right Pre-Employment Tests (free template)","TRANSPLANT",
  "Skills-to-assessment mapping",
  ["350","298","1543","1810","2358","2341","2353","1901","2388","169","801","856","1546","1556","1561","1530","662"]),
 ("Skills Gap Analysis Template + Role-by-Role Assessment Map for Hiring Teams","CORE",
  "Skills gap analysis / pre-hire gap test",
  ["2130","1979","2403"]),
 ("Skills-Based Hiring Readiness Audit: Self-Assessment + Degree-Requirement Removal Template","CORE",
  "Skills-based hiring readiness / transformation",
  ["1974","360","425","1508"]),
 ("Degree vs. Skills & Credential Verification: Decision Guide + Where Skills Tests Fill the Gaps","CORE",
  "Degree vs skills / credential verification",
  ["1869","1430"]),
 ("The Complete Hiring Process Guide: Step-by-Step with Assessment Templates & Scorecard Examples","CORE",
  "Complete hiring process guide",
  ["1482","405","57","1545","2468","2345"]),
 ("How to Improve Your Hiring Process: Evidence-Based Fixes & Bottleneck Diagnostic (with Templates)","CORE",
  "Improve / fix the hiring process",
  ["1387","1370"]),
 ("12 Core Hiring & Assessment Decisions Every Talent Team Faces (method comparison guide)","TRANSPLANT",
  "Core hiring decisions / playbook",
  ["447","1529"]),
 ("Hiring Process Automation Playbook: Which Stages Save the Most Time (with Checklist)","TRANSPLANT",
  "Hiring process automation",
  ["1388","2461","1908"]),
 ("Candidate Shortlisting Playbook: Scoring Matrix & Assessment-Based Criteria by Role","CORE",
  "Candidate shortlisting",
  ["187"]),
 ("Structured Interview Scorecard Kit: Competency Question Bank + Scoring Rubrics (with Validity Data)","CORE",
  "Structured interview scorecards & question banks",
  ["503","1559","641","717","840","2136","2359","1596","2333","1624"]),
 ("Interview Red Flags Scorecard: 30 Signals, Severity Ratings & Follow-Up Questions","CORE",
  "Interview red flags scorecard",
  ["2446"]),
 ("Structured vs. Unstructured Interview Benchmark: Pass Rates, Predictive Validity & Bias Data","CORE",
  "Structured vs unstructured interview",
  ["1946"]),
 ("Video vs. AI vs. In-Person Interviews: Accuracy, Bias & Time-to-Hire by Format","ADJACENT",
  "Interview format comparison",
  ["714","1008"]),
 ("Evidence-Based Hiring Playbook: Predictive Methods Ranked by Validity + Selection Checklist","CORE",
  "Evidence-based hiring / validity ranking",
  ["642","813","647"]),
 ("Adaptive vs. Fixed-Form Assessment Comparison: When to Use Each (+ What the Score Report Tells You)","CORE",
  "Adaptive vs fixed-form assessment",
  ["568"]),
 ("Assessment Length & Dropout Rate Calculator: Find Your Optimal Test Battery per Stage","CORE",
  "Assessment length / dropout calculator",
  ["644"]),
 ("Hiring Assessment & Psychometrics Glossary: 80 Terms Every Recruiter Should Know (with Test Examples)","ADJACENT",
  "Hiring assessment glossary",
  ["288"]),
 ("Free Cognitive Aptitude Practice Test: Timed Sample Questions with Explanations & Benchmarks","CORE",
  "Free test — cognitive / aptitude",
  ["534","1819","1997","61","66","721"]),
 ("Free Pre-Employment Test Prep: Type-by-Type Practice Questions with Timed Simulator","CORE",
  "Free test-prep simulator (multi-type)",
  ["551","593"]),
 ("Personality Tests for Hiring: Validity Comparison + Sample Questions for the Major Frameworks","CORE",
  "Personality test — validity & samples",
  ["1817","100","154","155","2432","2453","794"]),
 ("Free Emotional Intelligence Assessment: Ability-Based Sample Test + Validity Comparison","CORE",
  "Free test — emotional intelligence",
  ["589","1956","607","663"]),
 ("Learning Agility Assessment: Sample Questions + Scoring Rubric for the 5 Korn Ferry Factors","CORE",
  "Learning agility assessment",
  ["1965"]),
 ("Free Typing Speed Test for Hiring + Benchmark WPM Data by Role (No Signup)","CORE",
  "Free test — typing speed",
  ["1830","105","2297"]),
 ("Free Grammar Skills Test for Hiring: Sample Questions + Role-Specific Cut-Score Guide","CORE",
  "Free test — grammar",
  ["771"]),
 ("Free Advanced Excel Skills Assessment: Sample Questions (VLOOKUP, Pivots, VBA) — No Signup","CORE",
  "Free test — Excel",
  ["1934","2285","2343"]),
 ("Free Numerical Reasoning Test for Hiring: Sample Questions by Difficulty + Role Benchmarks","CORE",
  "Free test — numerical reasoning",
  ["838"]),
 ("Free Verbal Reasoning Skills Test: Sample Questions, Role-Level Benchmarks & Shareable Result","CORE",
  "Free test — verbal reasoning",
  ["2364"]),
 ("How to Assess Problem-Solving Skills in Hiring: Sample Test Questions + Scoring Rubric by Role","CORE",
  "Skill guide — problem-solving",
  ["1803","31","1816","2458","2309"]),
 ("How to Test the 8 Most In-Demand Soft Skills in Hiring: Methods, Sample Questions & Rubrics","TRANSPLANT",
  "Skill guide — soft skills (general)",
  ["764","772","170","352"]),
 ("Assessing Communication Skills: Question Bank & Scoring Rubric for Active Listening & Clarity","ADJACENT",
  "Skill guide — communication / active listening",
  ["1891","833","2327","2351"]),
 ("Assessing Teamwork Skills When Hiring: Sample Test Questions & Scoring Rubric","CORE",
  "Skill guide — teamwork",
  ["1928"]),
 ("Adaptability in Hiring: Structured Interview Question Bank + Scoring Rubric","ADJACENT",
  "Skill guide — adaptability",
  ["1820","587"]),
 ("Attention to Detail Assessment Kit: Sample Test Questions + Interview Rubric for Hiring","ADJACENT",
  "Skill guide — attention to detail",
  ["30","2289"]),
 ("Analytical & Critical Thinking in Hiring: What It Is + How to Assess It + Sample Questions","CORE",
  "Skill guide — analytical / critical thinking",
  ["1595","108"]),
 ("Writing & Content Skills Assessment Guide for Hiring: Sample Prompts + Scoring Rubric by Role","ADJACENT",
  "Skill guide — writing / content",
  ["48","1960"]),
 ("Culture Add vs. Culture Fit: Assessment Framework + Structured Interview Question Bank","ADJACENT",
  "Culture fit / culture add assessment",
  ["1962","2022","1967"]),
 ("Customer Service Skills Assessment: Sample Questions + Structured Interview Scorecard","CORE",
  "Role kit — customer service",
  ["22","56"]),
 ("HR & Recruiter Skills Self-Assessment Test for Talent Acquisition Professionals","ADJACENT",
  "Role kit — HR / TA / recruiter",
  ["477","769","496","1836"]),
 ("Free Virtual Assistant Skills Assessment: Sample Tasks + Scoring Guide for Hiring Remote VAs","CORE",
  "Role kit — virtual assistant",
  ["1833"]),
 ("Free Remote Work Skills Test: Sample Questions for 5 Core Remote Competencies + Benchmarks","CORE",
  "Role kit — remote worker",
  ["1848","1616"]),
 ("Free Hospitality Manager Skills Assessment: Guest Experience, Team & Revenue Sample Questions","CORE",
  "Role kit — hospitality manager",
  ["1959"]),
 ("Free QA Engineer Skills Assessment: Test Planning, Bug Reporting & Automation Sample Questions","CORE",
  "Role kit — QA engineer",
  ["1969"]),
 ("Management & Leadership Skills Assessment Kit: Sample Questions + Scorecard for Hiring Leaders","CORE",
  "Role kit — management / leadership",
  ["1824","762","798","2016","1972","1339","1802"]),
 ("Tech-Role Skills Assessment Kit Library: Unified Blueprints with Sample Questions & Scoring","CORE",
  "Role kit — tech role blueprints (library)",
  ["205","268","256","257","258","259","260","261","262","263","264","265","266","267","269","270"]),
 ("How to Choose and Run a Coding Skills Test: End-to-End Guide with Sample Questions & Rubric","CORE",
  "Coding skills test — guide & buyer's guide",
  ["2267","1804","2380","2427","2394","144","158","180","2288"]),
 ("Tech Hiring: Which Skills Assessments Predict Performance for AI, Cloud & Cyber Roles","CORE",
  "Tech skills assessment guide",
  ["902","1550","1931","2284","2382","2462","2438","2348","2466"]),
 ("True Cost of Hiring a Software Developer: ROI Calculator + Free Java & Python Test Samples","CORE",
  "Cost of hiring a developer",
  ["1072"]),
 ("AI & Automation Skills Assessment Test for Hiring (Free + Role-Specific Sample Questions)","ADJACENT",
  "Skill guide — AI / automation roles",
  ["510"]),
 ("Job Simulation & Work-Sample Assessment Templates: Role-Ready Kits with Scoring Rubrics","CORE",
  "Job simulation / work-sample templates",
  ["32","2310","2282"]),
 ("Multi-Measure Assessment Kit Library: Pre-Built Test Combinations for Common Roles","CORE",
  "Multi-measure / combination kits",
  ["1932","1919"]),
 ("Hiring in the Age of AI Resumes: Skills Tests That Catch What AI Polishes (with Detection Data)","CORE",
  "Resume vs skills / AI resumes",
  ["1885"]),
 ("Hiring Funnel Assessment Planner: Which Skills Tests to Run at Each Hiring Stage (Checklist)","CORE",
  "Hiring funnel assessment planner",
  ["1855","1002"]),
 ("Employee Referral Programs That Hire Well: How to Screen Referred Candidates with Skills Tests","ADJACENT",
  "Referral programs + skills screening",
  ["1490","1496","1499","1403"]),
 ("Job Requisition to Assessment Playbook: Template + Skills-Test Selection by Role Type","CORE",
  "Candidate profile / job requisition mapping",
  ["1625"]),
 ("Screening Nonlinear, Passive & Global Candidates: Skills-Based Assessment Frameworks","ADJACENT",
  "Screening nonlinear / passive / global candidates",
  ["2017","2299","2280","2023"]),
 ("Bulk Hiring Assessment Playbook: Screen 500+ Candidates with Skills Tests & AI Interviews","CORE",
  "Bulk / high-volume hiring assessment",
  ["2338"]),
 ("Skills-Based Hiring Case Study Hub: Companies with Standardized Before/After KPIs by Industry","CORE",
  "Skills-based hiring case studies",
  ["1829","2277"]),
 ("Skills-Based Hiring Change-Management Kit: Objection Scripts, Stakeholder Deck & Rollout Checklist","CORE",
  "Change management for skills-based hiring",
  ["1990"]),
 ("How to Use Free Skills Assessments as a Recruitment Marketing Channel","ADJACENT",
  "Free tests as recruitment marketing",
  ["1452"]),
 ("Merit-Based Hiring in Tech: What the Evidence Shows on Skills-Test Validity & Quality-of-Hire","CORE",
  "Merit-based / defensible hiring evidence",
  ["2448"]),
 ("Acquihire Skills Due-Diligence Toolkit: How to Assess the Team You're Buying","ADJACENT",
  "Acquihire due diligence",
  ["2328"]),
 ("Assessment Automation Guide for In-House Teams: Auto-Dispatch, Score & Push to ATS","ADJACENT",
  "Assessment automation (ATS)",
  ["1357"]),
]

# Fix the two clusters that used placeholder lists for the 'challenges' and merit dup:
C = [c for c in C if c[3] and c[3] != ["x"]]

# Post-fix: the 'Technical & Hiring Challenges' cluster needs row 1387 — but 1387 is used by 'Improve hiring process'.
# Resolve: keep 1387 in 'Improve hiring process'; the challenges cluster instead owns nothing new -> drop it.
# Also 'Merit' (2448) and 'Readiness' (2448) and 'Evidence-based(813)' vs 'When to use(813)' could collide; the validator below catches dups.

seen = {}
out = []
for idea, fit, subj, ids in C:
    real = [i for i in ids if i and i in rows]
    bad = [i for i in ids if i and i not in rows]
    if bad:
        raise SystemExit(f"UNKNOWN ids in '{idea}': {bad}")
    for i in real:
        if i in seen:
            raise SystemExit(f"DUP {i}: '{idea}' vs '{seen[i]}'")
        seen[i] = idea
    if real:
        out.append({"idea": idea, "brand_fit": fit, "our_subject": subj, "member_rowids": real})

missing = sorted([i for i in rows if i not in seen], key=int)
if missing:
    raise SystemExit(f"MISSING {len(missing)}: {missing}")

with open(OUT, "w") as f:
    for o in out:
        f.write(json.dumps(o, ensure_ascii=False) + "\n")
print(f"clusters={len(out)} covered={len(seen)}/{len(rows)} all={len(seen)==len(rows)}")
